services:
  database:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      POSTGRES_USER: "${POSTGRES_DB_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_DB_PASSWORD}"
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-network
      
volumes:
  db-data:

networks:
  spring-network:
    driver: bridge